POST http://localhost/puzzles/api/login
content-type: application/json
accept-type: application/json

{
    "username": "123456",
    "password": "123456"
}

###

POST http://localhost/puzzles/api/register
content-type: application/json
accept-type: application/json

{
    "password": "123456"
}
